# Generated by Django 2.2.2 on 2019-08-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suratpengantar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan_surat', models.CharField(max_length=12)),
                ('atas_nama', models.CharField(max_length=255, null=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.Ktp')),
            ],
        ),
    ]
