# Generated by Django 2.2.2 on 2019-08-20 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('suratpengantar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratpengantar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 8, 20, 14, 19, 16, 446860, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suratpengantar',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
