# Generated by Django 2.2.2 on 2019-08-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suratpengantar', '0002_auto_20190820_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suratpengantar',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='suratpengantar',
            name='update_at',
        ),
    ]
