# Generated by Django 2.2.2 on 2019-08-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suratpengantar', '0003_auto_20190820_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='suratpengantar',
            name='scan_surat',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
