# Generated by Django 2.2.2 on 2019-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suratpengantar', '0004_suratpengantar_scan_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratpengantar',
            name='scan_surat',
            field=models.ImageField(blank=True, default='/noimage.png', null=True, upload_to='scan_surat_pengantar/'),
        ),
    ]
