# Generated by Django 2.2.2 on 2019-08-09 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_kk', models.IntegerField(unique=True)),
                ('alamat', models.TextField()),
                ('rt', models.CharField(choices=[('1', 'RT 01'), ('2', 'RT 02'), ('3', 'RT 03'), ('4', 'RT 04'), ('5', 'RT 05'), ('6', 'RT 06'), ('7', 'RT 07'), ('8', 'RT 08'), ('9', 'RT 09')], max_length=3)),
                ('rw', models.CharField(default='RW 016', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Ktp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.IntegerField(unique=True)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.DateField()),
                ('tempat_lahir', models.CharField(max_length=15)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki Laki'), ('P', 'Perempuan')], max_length=10)),
                ('golongan_darah', models.CharField(choices=[('1', '-'), ('2', 'A'), ('3', 'B'), ('4', 'AB'), ('5', 'O')], default=1, max_length=2)),
                ('alamat', models.CharField(max_length=50)),
                ('rt', models.CharField(blank=True, choices=[('1', 'RT 01'), ('2', 'RT 02'), ('3', 'RT 03'), ('4', 'RT 04'), ('5', 'RT 05'), ('6', 'RT 06'), ('7', 'RT 07'), ('8', 'RT 08'), ('9', 'RT 09')], max_length=3, null=True)),
                ('rw', models.CharField(default='RW 016', max_length=7)),
                ('kecamatan', models.CharField(default='Grogol Petamburan', max_length=25)),
                ('agama', models.CharField(choices=[('1', '-'), ('2', 'Islam'), ('3', 'Kristen Protestan'), ('4', 'Hindu'), ('5', 'Budha'), ('6', 'Katolik'), ('7', 'Kong Hu Cu')], default=1, max_length=15)),
                ('status_perkawinan', models.CharField(choices=[('BK', 'Belum Kawin'), ('K', 'Kawin ')], default=1, max_length=11)),
                ('pekerjaan', models.CharField(max_length=25)),
                ('kewarganegaraan', models.CharField(choices=[('WNI', 'Warga Negara Indonesia'), ('WNA', 'Warga Negara Asing')], max_length=3)),
                ('masa_berlaku', models.CharField(default='Seumur Hidup', editable=False, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ktpkk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_kepala_keluarga', models.BooleanField(default=False)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.Ktp', unique=True)),
                ('nomor_kk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.Kk')),
            ],
        ),
    ]
