# Generated by Django 2.2.2 on 2019-08-13 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_auto_20190813_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='is_kepala_keluarga',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='kk',
            name='nik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warga.Ktp', unique=True),
        ),
    ]
