# Generated by Django 2.2.2 on 2019-08-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0005_auto_20190820_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ktp',
            name='nik',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
