# Generated by Django 2.2.2 on 2019-08-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0006_auto_20190820_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kk',
            name='nomor_kk',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
