# Generated by Django 2.2.2 on 2019-08-22 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0007_auto_20190820_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='kk',
            name='scan_kk',
            field=models.ImageField(blank=True, default='/noimage.png', null=True, upload_to='scan_kk/'),
        ),
        migrations.AddField(
            model_name='ktp',
            name='scan_ktp',
            field=models.ImageField(blank=True, default='/noimage.png', null=True, upload_to='scan_ktp/'),
        ),
    ]
